# Generated by Django 4.2.5 on 2023-10-26 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EaUser",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_id", models.BigIntegerField()),
                ("login", models.BigIntegerField()),
                ("delete_flg", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ea_user",
            },
        ),
        migrations.CreateModel(
            name="EaUserProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("family_name", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("family_name_kana", models.CharField(max_length=255, null=True)),
                ("first_name_kana", models.CharField(max_length=255, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ea_user_profile",
                        to="ea.eauser",
                    ),
                ),
            ],
            options={
                "db_table": "ea_user_profile",
            },
        ),
        migrations.CreateModel(
            name="EaData",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_id", models.BigIntegerField()),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("ticket", models.CharField(blank=True, max_length=255, null=True)),
                ("symbol", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "magic_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lots", models.CharField(blank=True, max_length=255, null=True)),
                ("swap", models.CharField(blank=True, max_length=255, null=True)),
                ("open_price", models.CharField(blank=True, max_length=255, null=True)),
                ("open_time", models.DateTimeField(blank=True, null=True)),
                (
                    "close_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                ("stop_loss", models.CharField(blank=True, max_length=255, null=True)),
                ("commission", models.CharField(blank=True, max_length=255, null=True)),
                ("expiration", models.CharField(blank=True, max_length=255, null=True)),
                ("profit", models.IntegerField(default=0)),
                (
                    "take_profit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comment", models.TextField(blank=True, max_length=1000, null=True)),
                ("delete_flg", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ea_data",
                        to="ea.eauser",
                    ),
                ),
            ],
            options={
                "db_table": "ea_data",
            },
        ),
    ]
