# Generated by Django 4.2.5 on 2023-10-25 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ea", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EaUserProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("family_name", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("family_name_kana", models.CharField(max_length=255, null=True)),
                ("first_name_kana", models.CharField(max_length=255, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ea_user_profile",
                        to="ea.eauser",
                    ),
                ),
            ],
            options={
                "db_table": "ea_user_profile",
            },
        ),
    ]
